## Class exercise 1: table
![](images/numpy_slice_ex.png)
- on the above image find the 5 different slicings using only the array slicing notation

In [5]:
import numpy as np

a = np.arange(10, 30).reshape(4, 5)

print('cube:\n',a)

red = a[0, 1:4]
teal = a[:,1::2]
green = a[0:3,2]
blue = a[0:-1:2,4]
yellow = a[0,0]

print('\nred:',red,'\nteal:',teal,'\ngreen:',green,'\nblue:',blue,'\nyellow:',yellow)

cube:
 [[10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]

red: [11 12 13] 
teal: [[11 13]
 [16 18]
 [21 23]
 [26 28]] 
green: [12 17 22] 
blue: [14 24] 
yellow: 10


## 3D
#### reshape can be done with multiple dimensions. Here is an example with 3d  
`a = np.arange(0, 27).reshape((3, 3, 3))`  
![](images/cube.png)

## Class exercise 2: cube
1. Slice out [12 13 14] from the above cube using only one slice. e.g: a[:,:,:]
2. Slice out [3 12 21].
3. Slice out all y-values where x is 2 and z is 0.

In [14]:
import numpy as np

a = np.arange(0, 27).reshape((3, 3, 3))

print(a)

Ex1 = a[1,1,:]
Ex2 = a[:,1,0]
Ex3 = a[0,:,2]

print('\nEx1:',Ex1,'\nEx2:',Ex2,'\nEx3:',Ex3)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]

Ex1: [12 13 14] 
Ex2: [ 3 12 21] 
Ex3: [2 5 8]
